function Init ()
    FFI = require ("ffi")
    BIT = require ("bit")
	GL = require ("lua/GL")
    local api_file = io.open ("API.h")
    local api_text = api_file:read ("*all")
    FFI.cdef (api_text)
    core = FFI.C

    core.Require ("Lib")
    core.Require ("Util")
    core.Require ("Loop")
    core.Require ("World")
    core.Require ("AStar")
    core.Require ("Camera")
    core.Require ("Sector")
    core.Require ("System")
    core.Require ("Sphere")
    core.Require ("KeyDefs")

    World = NewWorld ()
	GSectorInit ()
	VSectorInit ()
	VImposterInit ()
	GPlanetInit ()
	TexInit ()
end
